version: "3.8"

services:
  # PostgreSQL database container
  esg-psql-db:
    image: postgres
    container_name: esg-psql-db
    restart: always # if container fails, start up again. Ensures data is always accessible
    environment: # application.properties will pick this up
      - POSTGRES_USER=esgtestuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_DB=esgcustomers
    ports:
      - "5432:5432"
